/*
 * generated by Xtext 2.10.0
 */
package de.htwg.xtext.validation

import de.htwg.xtext.setGame.Model
import de.htwg.xtext.setGame.SetGamePackage
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class SetGameValidator extends AbstractSetGameValidator {

	public static val MIN_NUMBER_OF_OPTION_VALUES = 3
	public static val ERROR_MESSAGE = "Need more option values. Could only generate %d cards (min. %d cards)"

	@Check
	def checkNumberOfOptionValues(Model model) {
		if (model.options.size == 0) {
			check(0, MIN_NUMBER_OF_OPTION_VALUES)
		} else {
			var values = count(model) 
			check(values, MIN_NUMBER_OF_OPTION_VALUES)
		}
	}
	
	def private count(Model model) {
		var values = 1;
		for (option : model.options) {
			values *= option.values.size
		}
		return values;
	}
	
	def private check(int values, int min) {
		if (values < min) {
			error(String::format(ERROR_MESSAGE, values, min), SetGamePackage.Literals.MODEL__OPTIONS)
		}
	}

}
