/*
 * generated by Xtext 2.10.0
 */
package de.htwg.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SetGameStandaloneSetup extends SetGameStandaloneSetupGenerated {

	def static void doSetup() {
		new SetGameStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
